name: SonarQube Analysis for PRs

# This workflow handles SonarCloud analysis for ALL pull requests (internal and fork).
#
# Why use workflow_run instead of running directly in teranode_pr_tests.yaml:
# - Fork PRs cannot access repository secrets (SONAR_TOKEN) for security reasons
# - workflow_run always runs in the base repository context with access to secrets
#
# How it works:
# 1. teranode_pr_tests.yaml runs on PR (fork or internal) and generates artifacts
# 2. When that completes, this workflow triggers with access to SONAR_TOKEN
# 3. Downloads artifacts and runs SonarQube scan with proper PR decoration

on:
  workflow_run:
    workflows: ["Teranode PR tests"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  GO_VERSION: "1.25.2"

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: teranode-runner
    # Only run if:
    # 1. The triggering workflow succeeded (ensures all artifacts were generated)
    # 2. It was triggered by a pull_request event (not push to main)
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    steps:

      - name: Get PR number and metadata
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.workflow_run.pull_requests[0].number;
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            core.setOutput('number', prNumber);
            core.setOutput('base', pr.data.base.ref);
            core.setOutput('head', pr.data.head.ref);
            core.setOutput('head_sha', pr.data.head.sha);

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr.outputs.base }}
          fetch-depth: 0

      - name: Checkout PR head
        run: |
          git fetch origin pull/${{ steps.pr.outputs.number }}/head:pr-${{ steps.pr.outputs.number }}
          git checkout pr-${{ steps.pr.outputs.number }}

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download golangci-lint report
        uses: actions/download-artifact@v4
        with:
          name: golangci-lint-report
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download filename check report
        uses: actions/download-artifact@v4
        with:
          name: sonar-filename-report
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.pullrequest.key=${{ steps.pr.outputs.number }}
            -Dsonar.pullrequest.branch=${{ steps.pr.outputs.head }}
            -Dsonar.pullrequest.base=${{ steps.pr.outputs.base }}

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@v1.2.0
        timeout-minutes: 10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
