name: Teranode main pull request tests

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read
  id-token: write

env:
  REPO: teranode
  SETTINGS_CONTEXT_DEFAULT: test
  GO_VERSION: "1.25.2"

jobs:
  golangci:
    name: lint
    runs-on: teranode-runner
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          only-new-issues: true
          args: --timeout=5m

  test:
    name: test
    runs-on: teranode-runner
    steps:
      - uses: actions/checkout@v4

      # Only login to Docker Hub for internal PRs to avoid rate limits.
      # Fork PRs won't have access to secrets and will skip this step.
      - name: Login to Docker Hub
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_ORG }}
          password: ${{ secrets.DOCKER_ORG_TOKEN }}

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Run Go tests
        run: make test
        continue-on-error: false

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out
          retention-days: 1

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: /tmp/teranode-test-results/test-results.txt
          retention-days: 2
      # - name: Publish Test Summary Results
      #   if: always()
      #   run: npx github-actions-ctrf ctrf-report.json

  smoketest:
    name: smoketest
    runs-on: teranode-runner
    steps:
      # Only login to Docker Hub for internal PRs to avoid rate limits.
      # Fork PRs won't have access to secrets and will skip this step.
      - name: Login to Docker Hub
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_ORG }}
          password: ${{ secrets.DOCKER_ORG_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: "false"

      - name: Run Smoke tests
        run: make smoketest
        continue-on-error: false
        env:
          settings_context: ${{ env.SETTINGS_CONTEXT_DEFAULT }}

      - name: Run Long tests
        run: make sequentialtest
        continue-on-error: false
        env:
          settings_context: ${{ env.SETTINGS_CONTEXT_DEFAULT }}

      - name: Upload smoketest results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoketest-results
          path: /tmp/teranode-test-results/smoketest-results.txt
          retention-days: 2

      - name: Upload sequentialtest results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sequentialtest-results
          path: /tmp/teranode-test-results/sequentialtest-results.txt
          retention-days: 2

  sonarqube:
    name: Sonarqube
    runs-on: teranode-runner
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Run filename check script
        run: |
          ./scripts/check_filenames.sh

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      # Re-run golangci-lint separately without exiting on errors and generating a report for use in Sonar
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=5m --issues-exit-code=0 --output.checkstyle.path=golangci-lint-report.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@v1.2.0
        timeout-minutes: 10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
