name: Teranode PR smoke tests

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read
  id-token: write

env:
  REPO: teranode
  SETTINGS_CONTEXT_DEFAULT: test
  GO_VERSION: "1.25.2"

jobs:
  smoketest:
    name: smoketest
    runs-on: teranode-runner
    steps:
      # Only login to Docker Hub for internal PRs to avoid rate limits.
      # Fork PRs won't have access to secrets and will skip this step.
      - name: Login to Docker Hub
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_ORG }}
          password: ${{ secrets.DOCKER_ORG_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: "false"

      - name: Run Smoke tests
        run: make smoketest
        continue-on-error: false
        env:
          settings_context: ${{ env.SETTINGS_CONTEXT_DEFAULT }}

      - name: Run Long tests
        run: make sequentialtest
        continue-on-error: false
        env:
          settings_context: ${{ env.SETTINGS_CONTEXT_DEFAULT }}

      - name: Upload smoketest results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoketest-results
          path: /tmp/teranode-test-results/smoketest-results.txt
          retention-days: 2

      - name: Upload sequentialtest results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sequentialtest-results
          path: /tmp/teranode-test-results/sequentialtest-results.txt
          retention-days: 2
